### ISSUE TITLE
Design a poster

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/pioneers#3]
Develop a poster template that includes the information from this spreadsheet, at least 1-2 images, and pleasing design that incorporates the Bootstrap logo. The template should exist in both 11x17 size, and 8.5x11 size.

WHEN COMPLETE: share the poster template, along with 2-3 instances of that template populated with rows from the spreadsheet.

SIGNOFF: Finalizing a design can take multiple rounds of feedback, so assume this will take some back-and-forth with me and the larger team. You do NOT need to wait before drafting the community engagement strategy in #4 .

**Comment by rrajesh1** [comment]
I have uploaded a poster template along with examples (see Version 3) to the GitHub repository. Please let me know any changes that need to be made. Thank you!

**Comment by schanzer** [comment]
@rrajesh1 make sure the poster includes ALL columns from the spreadsheet - especially any attributions.

**Comment by rrajesh1** [comment]
Should the source and external contributor columns also be included?

**Comment by schanzer** [comment]
Source should, but I think we can skip attributions for the poster templates themselves.

**Comment by rrajesh1** [comment]
Could you clarify what you mean by attributions?

**Comment by schanzer** [comment]
I mean the external contributor columns (which we use to show attribution). Or perhaps include them only in a small footer near the bottom of the page.

**Comment by rrajesh1** [comment]
Got it, thank you! I will make those changes as soon as possible. Should the boolean columns describing the different populations also be incorporated into the poster?

**Comment by schanzer** [comment]
No need. I think that's more for internal auditing.

**Comment by rrajesh1** [comment]
Got it thank you! I just pushed a new version including the sources and attributions columns.

**Comment by schanzer** [comment]
@rrajesh1 this is looking really nice!!!

I know you're starting classes now, so we should think about how to bring this project to a good conclusion before you hand it off. As far as I'm concerned, you've already hit it out of the park in a lot of ways and I'm really excited to see your progress!

Let's not worry about the social media stuff for now. Instead, I'm going to make one more Git issue that can be your "closeout issue". Sound good?
